export const DASHBOARD_REQUEST_START = "DASHBOARD_REQUEST_START";
export const DASHBOARD_REQUEST_SUCCESS = "DASHBOARD_REQUEST_SUCCESS";
export const DASHBOARD_REQUEST_FAILURE = "DASHBOARD_REQUEST_FAILURE";
