export const MEMBERSHIP_REQUEST_START = "MEMBERSHIP_REQUEST_START";
export const MEMBERSHIP_REQUEST_SUCCESS = "MEMBERSHIP_REQUEST_SUCCESS";
export const MEMBERSHIP_REQUEST_FAILURE = "MEMBERSHIP_REQUEST_FAILURE";
