export const PRIORITY_REQUEST_START = "PRIORITY_REQUEST_START";
export const PRIORITY_REQUEST_SUCCESS = "PRIORITY_REQUEST_SUCCESS";
export const PRIORITY_REQUEST_FAILURE = "PRIORITY_REQUEST_FAILURE";
